# Generated by Django 5.2.6 on 2025-10-18 12:44

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('website_traffic', 'Трафик сайта'), ('social_media', 'Социальные сети'), ('email', 'Email рассылки'), ('conversion', 'Конверсия'), ('engagement', 'Вовлеченность'), ('reach', 'Охват'), ('impressions', 'Показы'), ('clicks', 'Клики'), ('shares', 'Репосты'), ('comments', 'Комментарии'), ('likes', 'Лайки'), ('donations', 'Пожертвования'), ('registrations', 'Регистрации'), ('other', 'Другое')], max_length=20, verbose_name='Тип метрики')),
                ('name', models.CharField(max_length=255, verbose_name='Название метрики')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Значение')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('date_recorded', models.DateTimeField(verbose_name='Дата записи')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Метрика кампании',
                'verbose_name_plural': 'Метрики кампаний',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='DigitalCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название кампании')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL слаг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.CharField(max_length=500, verbose_name='Краткое описание')),
                ('campaign_type', models.CharField(choices=[('awareness', 'Информирование'), ('fundraising', 'Сбор средств'), ('advocacy', 'Адвокация'), ('education', 'Образование'), ('community', 'Сообщество'), ('research', 'Исследование'), ('innovation', 'Инновации'), ('sustainability', 'Устойчивость'), ('other', 'Другое')], max_length=20, verbose_name='Тип кампании')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('planning', 'Планирование'), ('active', 'Активная'), ('paused', 'Приостановлена'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('planned_duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Планируемая продолжительность (дни)')),
                ('goal_description', models.TextField(verbose_name='Описание целей')),
                ('target_audience', models.CharField(max_length=500, verbose_name='Целевая аудитория')),
                ('expected_impact', models.TextField(verbose_name='Ожидаемое воздействие')),
                ('impact_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=10, verbose_name='Уровень воздействия')),
                ('budget_planned', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Запланированный бюджет')),
                ('budget_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Потраченный бюджет')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='digital_campaigns/', verbose_name='Главное изображение')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='digital_campaigns/banners/', verbose_name='Баннер')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('website_visits', models.PositiveIntegerField(default=0, verbose_name='Посещения сайта')),
                ('social_media_reach', models.PositiveIntegerField(default=0, verbose_name='Охват в соцсетях')),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Уровень вовлеченности (%)')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Конверсия (%)')),
                ('actual_impact', models.TextField(blank=True, verbose_name='Фактическое воздействие')),
                ('lessons_learned', models.TextField(blank=True, verbose_name='Уроки')),
                ('success_factors', models.TextField(blank=True, verbose_name='Факторы успеха')),
                ('challenges_faced', models.TextField(blank=True, verbose_name='Вызовы')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичная')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Цифровая кампания',
                'verbose_name_plural': 'Цифровые кампании',
                'ordering': ['-created_at'],
            },
        ),
    ]
