# Generated by Django 5.2.6 on 2025-10-18 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digital_campaigns', '0001_initial'),
        ('donations', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcampaign',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем'),
        ),
        migrations.AddField(
            model_name='digitalcampaign',
            name='related_donation_campaigns',
            field=models.ManyToManyField(blank=True, to='donations.donationcampaign', verbose_name='Связанные кампании пожертвований'),
        ),
        migrations.AddField(
            model_name='digitalcampaign',
            name='related_programs',
            field=models.ManyToManyField(blank=True, to='programs.program', verbose_name='Связанные программы'),
        ),
        migrations.AddField(
            model_name='campaignmetric',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='digital_campaigns.digitalcampaign', verbose_name='Кампания'),
        ),
    ]
