# Generated by Django 5.2.6 on 2025-10-18 12:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название партнера')),
                ('name_kg', models.CharField(blank=True, max_length=255, verbose_name='Название партнера (КГ)')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Название партнера (EN)')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Логотип партнера')),
                ('category', models.CharField(choices=[('civil_organizations', 'Организации Гражданского Общества'), ('government_agencies', 'Государственные органы'), ('international_organizations', 'Международные Организации'), ('foreign_governments', 'Иностранные Правительства'), ('corporate_donors', 'Корпоративные доноры'), ('other_organizations', 'Другие организации')], max_length=100, verbose_name='Категория партнера')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
    ]
