# Generated by Django 5.2.6 on 2025-10-18 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.donationcampaign', verbose_name='Кампания'),
        ),
        migrations.AddField(
            model_name='donationtransaction',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='donations.donation', verbose_name='Пожертвование'),
        ),
        migrations.AddField(
            model_name='donorcardhistory',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_history', to='donations.donation', verbose_name='Пожертвование'),
        ),
        migrations.AddField(
            model_name='f2fcoordinator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='donation',
            name='f2f_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.f2fcoordinator', verbose_name='F2F координатор'),
        ),
        migrations.AddField(
            model_name='donation',
            name='f2f_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.f2flocation', verbose_name='F2F локация'),
        ),
        migrations.AddField(
            model_name='f2fsession',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.f2fcoordinator', verbose_name='Координатор'),
        ),
        migrations.AddField(
            model_name='f2fsession',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.f2flocation', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='f2flocation',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.f2fzone', verbose_name='Зона'),
        ),
        migrations.AddField(
            model_name='f2fcoordinator',
            name='assigned_zones',
            field=models.ManyToManyField(blank=True, to='donations.f2fzone', verbose_name='Назначенные зоны'),
        ),
        migrations.AddField(
            model_name='recurringconsentlog',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to='donations.donation', verbose_name='Пожертвование'),
        ),
        migrations.AddIndex(
            model_name='donorcardhistory',
            index=models.Index(fields=['donation'], name='donations_d_donatio_b295e6_idx'),
        ),
        migrations.AddIndex(
            model_name='donorcardhistory',
            index=models.Index(fields=['change_type'], name='donations_d_change__fda47f_idx'),
        ),
        migrations.AddIndex(
            model_name='donorcardhistory',
            index=models.Index(fields=['created_at'], name='donations_d_created_adc578_idx'),
        ),
        migrations.AddIndex(
            model_name='donorcardhistory',
            index=models.Index(fields=['salesforce_synced'], name='donations_d_salesfo_ff8f10_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donation_code'], name='donations_d_donatio_3fca06_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor_email'], name='donations_d_donor_e_914ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status'], name='donations_d_status_73ca83_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['is_recurring'], name='donations_d_is_recu_0043ad_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['created_at'], name='donations_d_created_26bd74_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringconsentlog',
            index=models.Index(fields=['donation'], name='donations_r_donatio_b9385a_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringconsentlog',
            index=models.Index(fields=['consent_type'], name='donations_r_consent_c40a76_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringconsentlog',
            index=models.Index(fields=['created_at'], name='donations_r_created_25919d_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringconsentlog',
            index=models.Index(fields=['ip_address'], name='donations_r_ip_addr_bae8f3_idx'),
        ),
    ]
