# Generated by Django 5.2.6 on 2025-10-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor_phone',
            field=models.CharField(max_length=20, verbose_name='Телефон донора'),
        ),
    ]
