# Generated by Django 5.2.6 on 2025-11-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donation_donor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='subscription_status',
            field=models.CharField(blank=True, choices=[('active', 'Активная'), ('paused', 'Приостановлена'), ('cancelled', 'Отменена'), ('pending', 'Ожидает активации'), ('expired', 'Истекла')], help_text='Применяется только для рекуррентных платежей', max_length=20, null=True, verbose_name='Статус подписки'),
        ),
    ]
