# Generated by Django 5.2.6 on 2025-12-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0004_donation_subscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="first_payment_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Используется для расчета следующих платежей в тот же день месяца",
                null=True,
                verbose_name="Дата первого успешного платежа",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="parent_order_id",
            field=models.CharField(
                blank=True,
                help_text="Order ID первого платежа в рекуррентной подписке. Используется для связи всех последующих платежей.",
                max_length=255,
                null=True,
                verbose_name="Родительский Order ID",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="recurring_profile_id",
            field=models.IntegerField(
                blank=True,
                help_text="pg_recurring_profile из ответа FreedomPay",
                null=True,
                verbose_name="ID рекуррентного профиля",
            ),
        ),
    ]
