# Generated by Django 5.2.6 on 2025-10-18 12:44

import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_kg', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (КГ)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (EN)')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание')),
                ('content_kg', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Содержание (КГ)')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Содержание (EN)')),
                ('excerpt', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('excerpt_kg', models.TextField(blank=True, verbose_name='Краткое описание (КГ)')),
                ('excerpt_en', models.TextField(blank=True, verbose_name='Краткое описание (EN)')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
                ('content_type', models.CharField(choices=[('news', 'Новость'), ('article', 'Статья'), ('story', 'История'), ('announcement', 'Объявление'), ('success_story', 'История успеха')], default='news', max_length=20, verbose_name='Тип контента')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'Архив'), ('scheduled', 'Запланировано')], default='draft', max_length=20, verbose_name='Статус')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закрепленная')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Запланировано на')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Количество лайков')),
                ('social_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок для соцсетей')),
                ('social_description', models.TextField(blank=True, verbose_name='Описание для соцсетей')),
                ('social_image', models.ImageField(blank=True, null=True, upload_to='news/social/', verbose_name='Изображение для соцсетей')),
                ('external_url', models.URLField(blank=True, verbose_name='Внешняя ссылка')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='news/attachments/', verbose_name='Вложение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('name_kg', models.CharField(blank=True, max_length=100, verbose_name='Название (КГ)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Название (EN)')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (КГ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Цвет')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Категория новостей',
                'verbose_name_plural': 'Категории новостей',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('is_main', models.BooleanField(default=False, verbose_name='Сделать главным?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Изображение новости',
                'verbose_name_plural': 'Изображения новостей',
                'ordering': ['-is_main', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('name_kg', models.CharField(blank=True, max_length=50, verbose_name='Название (КГ)')),
                ('name_en', models.CharField(blank=True, max_length=50, verbose_name='Название (EN)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Цвет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Тег новостей',
                'verbose_name_plural': 'Теги новостей',
                'ordering': ['name'],
            },
        ),
    ]
