# Generated by Django 5.2.6 on 2025-10-18 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_news', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddIndex(
            model_name='newscategory',
            index=models.Index(fields=['slug'], name='news_newsca_slug_5c0a14_idx'),
        ),
        migrations.AddIndex(
            model_name='newscategory',
            index=models.Index(fields=['is_active'], name='news_newsca_is_acti_354c69_idx'),
        ),
        migrations.AddIndex(
            model_name='newscategory',
            index=models.Index(fields=['sort_order'], name='news_newsca_sort_or_5d757a_idx'),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.newscategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news', verbose_name='Новость'),
        ),
        migrations.AddIndex(
            model_name='newstag',
            index=models.Index(fields=['slug'], name='news_newsta_slug_6443f7_idx'),
        ),
        migrations.AddIndex(
            model_name='newstag',
            index=models.Index(fields=['is_active'], name='news_newsta_is_acti_98501e_idx'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news', to='news.newstag', verbose_name='Теги'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['slug'], name='news_news_slug_915ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['status'], name='news_news_status_b581f2_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['published_at'], name='news_news_publish_377f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_featured'], name='news_news_is_feat_17225d_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['category'], name='news_news_categor_5f9b52_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['content_type'], name='news_news_content_4212ff_idx'),
        ),
    ]
