# Generated by Django 5.2.6 on 2025-10-18 12:44

import datetime
import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('birth_date', models.DateField()),
                ('preferred_language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('ky', 'Kyrgyz')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='F2FCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='ID сотрудника')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('on_leave', 'В отпуске'), ('suspended', 'Приостановлен')], default='active', max_length=20, verbose_name='Статус')),
                ('experience_level', models.CharField(choices=[('trainee', 'Стажер'), ('junior', 'Младший'), ('middle', 'Средний'), ('senior', 'Старший'), ('lead', 'Ведущий')], default='trainee', max_length=20, verbose_name='Уровень опыта')),
                ('hire_date', models.DateField(verbose_name='Дата найма')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('monthly_target', models.PositiveIntegerField(default=50, verbose_name='Месячная цель (регистраций)')),
                ('current_month_registrations', models.PositiveIntegerField(default=0, verbose_name='Регистраций в текущем месяце')),
                ('total_registrations', models.PositiveIntegerField(default=0, verbose_name='Всего регистраций')),
                ('success_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Коэффициент успеха (%)')),
                ('device_id', models.CharField(blank=True, max_length=100, verbose_name='ID устройства')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('offline_mode_enabled', models.BooleanField(default=True, verbose_name='Офлайн режим включен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'F2F Координатор',
                'verbose_name_plural': 'F2F Координаторы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='F2FCoordinatorRegionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(verbose_name='Дата назначения')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной регион')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Назначение координатора на регион',
                'verbose_name_plural': 'Назначения координаторов на регионы',
            },
        ),
        migrations.CreateModel(
            name='F2FDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Дата отчета')),
                ('total_approaches', models.PositiveIntegerField(default=0, verbose_name='Всего подходов')),
                ('successful_registrations', models.PositiveIntegerField(default=0, verbose_name='Успешных регистраций')),
                ('rejected_approaches', models.PositiveIntegerField(default=0, verbose_name='Отказов')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('break_duration', models.DurationField(default=datetime.timedelta(0), verbose_name='Продолжительность перерывов')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('weather_conditions', models.CharField(blank=True, max_length=100, verbose_name='Погодные условия')),
                ('foot_traffic_assessment', models.CharField(blank=True, choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=20, verbose_name='Оценка пешеходного трафика')),
                ('is_synced', models.BooleanField(default=False, verbose_name='Синхронизировано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Ежедневный отчет F2F',
                'verbose_name_plural': 'Ежедневные отчеты F2F',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='F2FLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('location_type', models.CharField(choices=[('mall', 'Торговый центр'), ('street', 'Улица'), ('park', 'Парк'), ('market', 'Рынок'), ('event', 'Мероприятие'), ('office', 'Офис'), ('other', 'Другое')], max_length=20, verbose_name='Тип локации')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Долгота')),
                ('status', models.CharField(choices=[('active', 'Активная'), ('inactive', 'Неактивная'), ('temp_closed', 'Временно закрыта'), ('under_review', 'На рассмотрении')], default='active', max_length=20, verbose_name='Статус')),
                ('working_hours_start', models.TimeField(verbose_name='Начало работы')),
                ('working_hours_end', models.TimeField(verbose_name='Конец работы')),
                ('working_days', models.CharField(default='1,2,3,4,5,6,7', max_length=20, verbose_name='Рабочие дни')),
                ('foot_traffic_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=20, verbose_name='Уровень пешеходного трафика')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'F2F Локация',
                'verbose_name_plural': 'F2F Локации',
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='F2FRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'F2F Регион',
                'verbose_name_plural': 'F2F Регионы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='F2FRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Номер регистрации')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другой'), ('P', 'Предпочитаю не указывать')], max_length=1, verbose_name='Пол')),
                ('preferred_language', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский'), ('ky', 'Кыргызский')], default='ru', max_length=2, verbose_name='Предпочитаемый язык')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс')),
                ('donation_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма пожертвования')),
                ('donation_type', models.CharField(choices=[('monthly', 'Ежемесячное'), ('quarterly', 'Ежеквартальное'), ('annual', 'Ежегодное'), ('one_time', 'Разовое')], max_length=20, verbose_name='Тип пожертвования')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Банковский перевод'), ('card', 'Банковская карта'), ('cash', 'Наличные'), ('mobile_payment', 'Мобильный платеж')], max_length=20, verbose_name='Способ оплаты')),
                ('consent_data_processing', models.BooleanField(default=False, verbose_name='Согласие на обработку данных')),
                ('consent_marketing', models.BooleanField(default=False, verbose_name='Согласие на маркетинг')),
                ('consent_newsletter', models.BooleanField(default=False, verbose_name='Согласие на рассылку')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processed', 'Обработано'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('is_synced', models.BooleanField(default=False, verbose_name='Синхронизировано')),
                ('sync_attempts', models.PositiveIntegerField(default=0, verbose_name='Попытки синхронизации')),
                ('last_sync_attempt', models.DateTimeField(blank=True, null=True, verbose_name='Последняя попытка синхронизации')),
                ('sync_error', models.TextField(blank=True, verbose_name='Ошибка синхронизации')),
                ('registration_source', models.CharField(default='f2f_mobile', max_length=50, verbose_name='Источник регистрации')),
                ('device_info', models.JSONField(blank=True, default=dict, verbose_name='Информация об устройстве')),
                ('gps_coordinates', models.JSONField(blank=True, default=dict, verbose_name='GPS координаты')),
                ('coordinator_notes', models.TextField(blank=True, verbose_name='Заметки координатора')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('registered_at', models.DateTimeField(verbose_name='Зарегистрировано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'F2F Регистрация',
                'verbose_name_plural': 'F2F Регистрации',
                'ordering': ['-registered_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='F2FRegistrationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('consent_form', 'Форма согласия'), ('signature', 'Подпись'), ('id_photo', 'Фото документа'), ('selfie', 'Селфи с координатором'), ('additional', 'Дополнительный документ')], max_length=20, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='f2f_documents/%Y/%m/%d/', verbose_name='Файл')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.PositiveIntegerField(verbose_name='Размер файла')),
                ('content_type', models.CharField(max_length=100, verbose_name='Тип контента')),
                ('is_synced', models.BooleanField(default=False, verbose_name='Синхронизировано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Документ F2F регистрации',
                'verbose_name_plural': 'Документы F2F регистраций',
            },
        ),
    ]
