# Generated by Django 5.2.6 on 2025-10-18 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='f2fcoordinator',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='donors.f2fcoordinator', verbose_name='Супервайзер'),
        ),
        migrations.AddField(
            model_name='f2fcoordinator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='f2f_coordinator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='f2fcoordinatorregionassignment',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.f2fcoordinator'),
        ),
        migrations.AddField(
            model_name='f2fdailyreport',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='donors.f2fcoordinator', verbose_name='Координатор'),
        ),
        migrations.AddField(
            model_name='f2fdailyreport',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.f2flocation', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='f2flocation',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.f2fregion', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='f2fcoordinatorregionassignment',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.f2fregion'),
        ),
        migrations.AddField(
            model_name='f2fcoordinator',
            name='assigned_regions',
            field=models.ManyToManyField(through='donors.F2FCoordinatorRegionAssignment', to='donors.f2fregion', verbose_name='Назначенные регионы'),
        ),
        migrations.AddField(
            model_name='f2fregistration',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='donors.f2fcoordinator', verbose_name='Координатор'),
        ),
        migrations.AddField(
            model_name='f2fregistration',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f2f_registrations', to='donors.donor', verbose_name='Связанный донор'),
        ),
        migrations.AddField(
            model_name='f2fregistration',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='donors.f2flocation', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='f2fregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f2f_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='f2fregistrationdocument',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='donors.f2fregistration', verbose_name='Регистрация'),
        ),
        migrations.AlterUniqueTogether(
            name='f2fdailyreport',
            unique_together={('coordinator', 'location', 'report_date')},
        ),
        migrations.AddIndex(
            model_name='f2flocation',
            index=models.Index(fields=['region', 'status'], name='donors_f2fl_region__4cdab7_idx'),
        ),
        migrations.AddIndex(
            model_name='f2flocation',
            index=models.Index(fields=['location_type'], name='donors_f2fl_locatio_79e678_idx'),
        ),
        migrations.AddIndex(
            model_name='f2flocation',
            index=models.Index(fields=['latitude', 'longitude'], name='donors_f2fl_latitud_35e8a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='f2fcoordinatorregionassignment',
            unique_together={('coordinator', 'region')},
        ),
        migrations.AddIndex(
            model_name='f2fcoordinator',
            index=models.Index(fields=['status', 'experience_level'], name='donors_f2fc_status_6aac4c_idx'),
        ),
        migrations.AddIndex(
            model_name='f2fcoordinator',
            index=models.Index(fields=['hire_date'], name='donors_f2fc_hire_da_954151_idx'),
        ),
        migrations.AddIndex(
            model_name='f2fcoordinator',
            index=models.Index(fields=['device_id'], name='donors_f2fc_device__6b7e58_idx'),
        ),
        migrations.AddIndex(
            model_name='f2fregistration',
            index=models.Index(fields=['coordinator', 'status'], name='donors_f2fr_coordin_3147e8_idx'),
        ),
        migrations.AddIndex(
            model_name='f2fregistration',
            index=models.Index(fields=['location', 'registered_at'], name='donors_f2fr_locatio_30b5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='f2fregistration',
            index=models.Index(fields=['email'], name='donors_f2fr_email_9dc3e6_idx'),
        ),
        migrations.AddIndex(
            model_name='f2fregistration',
            index=models.Index(fields=['phone'], name='donors_f2fr_phone_bc7697_idx'),
        ),
        migrations.AddIndex(
            model_name='f2fregistration',
            index=models.Index(fields=['is_synced'], name='donors_f2fr_is_sync_a6fd32_idx'),
        ),
        migrations.AddIndex(
            model_name='f2fregistration',
            index=models.Index(fields=['registration_number'], name='donors_f2fr_registr_c0d906_idx'),
        ),
    ]
