# Generated by Django 5.2.6 on 2025-10-18 12:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('contact_type', models.CharField(choices=[('general', 'Общий вопрос'), ('donation', 'Вопрос о пожертвованиях'), ('volunteer', 'Волонтерство'), ('partnership', 'Партнерство'), ('complaint', 'Жалоба'), ('suggestion', 'Предложение'), ('other', 'Другое')], default='general', max_length=20, verbose_name='Тип обращения')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Телефон'), ('any', 'Любой способ')], default='email', max_length=20, verbose_name='Предпочитаемый способ связи')),
                ('consent_data_processing', models.BooleanField(default=False, verbose_name='Согласие на обработку данных')),
                ('consent_marketing', models.BooleanField(default=False, verbose_name='Согласие на маркетинг')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В обработке'), ('responded', 'Отвечено'), ('closed', 'Закрыто'), ('spam', 'Спам')], default='new', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=20, verbose_name='Приоритет')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, verbose_name='Источник')),
                ('captcha_token', models.CharField(blank=True, max_length=255, verbose_name='Токен капчи')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Обнаружен как бот')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Внутренние заметки')),
                ('response_message', models.TextField(blank=True, verbose_name='Ответ')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email отправлен')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки email')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('name_kg', models.CharField(blank=True, max_length=100, verbose_name='Название (КГ)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Название (EN)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('email_recipients', models.TextField(blank=True, help_text='Список email через запятую для уведомлений', verbose_name='Email получатели')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Категория обратной связи',
                'verbose_name_plural': 'Категории обратной связи',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('office_type', models.CharField(choices=[('main_office', 'Главный офис'), ('coordination_office', 'Координационный офис'), ('children_village', 'Детская деревня'), ('educational_complex', 'Учебно-воспитательный комплекс'), ('other', 'Другое')], default='other', max_length=30, verbose_name='Тип офиса')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='Время работы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_main_office', models.BooleanField(default=False, verbose_name='Главный офис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Офис/Локация',
                'verbose_name_plural': 'Офисы/Локации',
                'ordering': ['order', 'name'],
            },
        ),
    ]
