# Generated by Django 5.2.6 on 2025-10-18 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Назначено'),
        ),
        migrations.AddField(
            model_name='contact',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Ответил'),
        ),
        migrations.AddIndex(
            model_name='contactcategory',
            index=models.Index(fields=['is_active'], name='contacts_co_is_acti_48eeac_idx'),
        ),
        migrations.AddIndex(
            model_name='contactcategory',
            index=models.Index(fields=['sort_order'], name='contacts_co_sort_or_5ba431_idx'),
        ),
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.contactcategory', verbose_name='Категория'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['status'], name='contacts_co_status_d675ed_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['priority'], name='contacts_co_priorit_5eda74_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['contact_type'], name='contacts_co_contact_d678b6_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['created_at'], name='contacts_co_created_71b3b6_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='contacts_co_email_25f973_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['is_bot'], name='contacts_co_is_bot_8c124f_idx'),
        ),
    ]
