# Generated by Django 5.2.6 on 2025-10-18 12:44

import apps.programs.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('network_type', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('telegram', 'Telegram'), ('vkontakte', 'ВКонтакте'), ('tiktok', 'TikTok'), ('other', 'Другое')], max_length=20, verbose_name='Тип социальной сети')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('icon', models.CharField(help_text='Название иконки для отображения (например: facebook, instagram)', max_length=50, verbose_name='Иконка')),
                ('custom_icon', models.FileField(blank=True, null=True, upload_to='social_networks/icons/', validators=[apps.programs.validators.validate_image_or_svg_file], verbose_name='Пользовательская иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('followers_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество подписчиков')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицированная')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
                'ordering': ['order', 'name'],
            },
        ),
    ]
