# Generated by Django 5.2.6 on 2025-10-26 09:55

import apps.qrcode.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', validators=[apps.qrcode.validators.SecureImageFileValidator()]),
        ),
    ]
