# Generated by Django 5.2.6 on 2025-10-26 10:01

import apps.qrcode.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0002_alter_qrcode_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Загрузите изображение QR-кода (JPG, PNG, GIF, BMP, SVG, WebP). Максимальный размер: 5MB', null=True, upload_to='qr_codes/', validators=[apps.qrcode.validators.SecureImageFileValidator()]),
        ),
    ]
