# Generated by Django 5.2.6 on 2025-10-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('option_type', models.CharField(choices=[('anniversary', 'Посвятите свой юбилей'), ('payroll', 'Пожертвование доли зарплаты'), ('non_monetary', 'Неденежные пожертвования'), ('one_time', 'Разовое пожертвование'), ('monthly', 'Ежемесячное пожертвование'), ('corporate', 'Корпоративное партнерство'), ('volunteer', 'Волонтерство'), ('other', 'Другое')], max_length=30, verbose_name='Тип пожертвования')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('coming_soon', 'Скоро'), ('inactive', 'Неактивно'), ('maintenance', 'На обслуживании')], default='active', max_length=20, verbose_name='Статус')),
                ('image', models.ImageField(upload_to='donation_options/', verbose_name='Изображение')),
                ('button_text', models.CharField(max_length=100, verbose_name='Текст кнопки')),
                ('button_url', models.URLField(blank=True, verbose_name='Ссылка кнопки')),
                ('is_button_enabled', models.BooleanField(default=True, verbose_name='Кнопка активна')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('detailed_description', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('benefits', models.TextField(blank=True, verbose_name='Преимущества')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Минимальная сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип пожертвования',
                'verbose_name_plural': 'Типы пожертвований',
                'ordering': ['order', 'title'],
            },
        ),
    ]
