# Generated by Django 5.2.6 on 2025-10-18 12:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('quote_text', models.TextField(verbose_name='Текст цитаты')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('author_position', models.CharField(max_length=200, verbose_name='Должность автора')),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='success_stories/', verbose_name='Фото автора')),
                ('story_type', models.CharField(choices=[('success', 'Успех'), ('family', 'Семья'), ('education', 'Образование'), ('personal_growth', 'Личностный рост'), ('community', 'Сообщество'), ('other', 'Другое')], default='success', max_length=20, verbose_name='Тип истории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'История успеха',
                'verbose_name_plural': 'Истории успеха',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
