# Generated by Django 5.2.7 on 2025-10-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstory',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL'),
        ),
    ]
