# Generated by Django 5.2.11 on 2026-03-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0002_allow_blank_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='success_stories/banners/', verbose_name='Баннер'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='full_story',
            field=models.TextField(blank=True, verbose_name='Полная история'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
