# Generated by Django 5.2.11 on 2026-03-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationFormContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_kg', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('description_kg', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('button_text', models.CharField(default='Пожертвовать', max_length=100)),
                ('button_text_kg', models.CharField(blank=True, max_length=100)),
                ('button_text_en', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Контент формы донатов',
                'verbose_name_plural': 'Контент формы донатов',
            },
        ),
    ]
