# Generated by Django 5.2.6 on 2025-10-25 08:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст вопроса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вопрос для отзыва',
                'verbose_name_plural': 'Вопросы для отзывов',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSpamProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP адрес')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='Количество попыток')),
                ('last_attempt', models.DateTimeField(auto_now=True, verbose_name='Последняя попытка')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='Заблокирован до')),
            ],
            options={
                'verbose_name': 'Защита от спама',
                'verbose_name_plural': 'Защита от спама',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('question', 'Отзыв с вопросом'), ('review', 'Отзыв-рецензия')], max_length=20, verbose_name='Тип отзыва')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(44)], verbose_name='Сообщение')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='feedback/photos/', verbose_name='Фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Анонимный')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('anonymous_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Анонимный ID')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbackquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
