# Generated by Django 5.2.6 on 2025-10-18 12:44

import apps.common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.CharField(max_length=50, unique=True, verbose_name='ID точки')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_kg', models.CharField(blank=True, max_length=200, verbose_name='Название (КГ)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Название (EN)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (КГ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
                ('image', models.ImageField(upload_to='location/')),
                ('x_percent', models.DecimalField(decimal_places=2, help_text='Позиция по X в процентах от ширины карты (0-100)', max_digits=5, verbose_name='X координата (%)')),
                ('y_percent', models.DecimalField(decimal_places=2, help_text='Позиция по Y в процентах от высоты карты (0-100)', max_digits=5, verbose_name='Y координата (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Точка карты',
                'verbose_name_plural': 'Точки карты',
                'ordering': ['order', 'name'],
            },
            bases=(apps.common.mixins.LocalizedFieldsMixin, models.Model),
        ),
    ]
