# Generated by Django 5.2.6 on 2025-10-18 12:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('subtitle', models.CharField(max_length=300, verbose_name='Подзаголовок')),
                ('principle_type', models.CharField(choices=[('mother', 'Мама'), ('siblings', 'Братья и Сестры'), ('home', 'Дом'), ('village', 'Деревня'), ('other', 'Другое')], max_length=20, verbose_name='Тип принципа')),
                ('icon', models.CharField(help_text='Название иконки для отображения', max_length=50, verbose_name='Иконка')),
                ('key_points', models.TextField(blank=True, verbose_name='Ключевые моменты')),
                ('impact', models.TextField(blank=True, verbose_name='Влияние')),
            ],
            options={
                'verbose_name': 'Принцип SOS',
                'verbose_name_plural': 'Принципы SOS',
                'ordering': ['order', 'principle_type'],
            },
        ),
    ]
