# Generated by Django 5.2.6 on 2025-10-18 12:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Фамилия')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Полное имя')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('user_type', models.CharField(choices=[('donor', 'Донор'), ('staff', 'Сотрудник'), ('volunteer', 'Волонтер'), ('partner', 'Партнер'), ('admin', 'Администратор')], default='donor', max_length=20, verbose_name='Тип пользователя')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другой')], max_length=10, null=True, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('preferred_language', models.CharField(choices=[('ru', 'Русский'), ('kg', 'Кыргызский'), ('en', 'Английский')], default='ru', max_length=2, verbose_name='Предпочитаемый язык')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Почтовый индекс')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='SMS уведомления')),
                ('newsletter_subscription', models.BooleanField(default=False, verbose_name='Подписка на новости')),
                ('consent_data_processing', models.BooleanField(default=False, verbose_name='Согласие на обработку данных')),
                ('consent_marketing', models.BooleanField(default=False, verbose_name='Согласие на маркетинг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Email подтвержден')),
                ('email_verification_token', models.CharField(blank=True, max_length=100, verbose_name='Токен подтверждения')),
                ('email_verification_expires', models.DateTimeField(blank=True, null=True, verbose_name='Срок действия токена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
                ('registration_source', models.CharField(choices=[('website', 'Сайт'), ('f2f', 'Face-to-Face'), ('admin', 'Админка'), ('api', 'API')], default='website', max_length=20, verbose_name='Источник регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='ConfirmCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('type', models.CharField(choices=[('email', 'Email')], default='email', max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Токен восстановления пароля',
                'verbose_name_plural': 'Токены восстановления пароля',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('authenticator', 'Authenticator App')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('disabled', 'Отключено'), ('enabled', 'Включено'), ('required', 'Обязательно'), ('temporarily_disabled', 'Временно отключено')], default='disabled', max_length=25)),
                ('is_required', models.BooleanField(default=False)),
                ('backup_codes_enabled', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('last_failed_attempt', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Двухфакторная аутентификация',
                'verbose_name_plural': 'Двухфакторная аутентификация',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorBackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('two_factor_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to='users.twofactorauth')),
            ],
            options={
                'verbose_name': 'Резервный код',
                'verbose_name_plural': 'Резервные коды',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code_type', models.CharField(choices=[('email', 'Email код'), ('sms', 'SMS код'), ('backup', 'Резервный код')], max_length=10)),
                ('encrypted_code', models.CharField(max_length=255)),
                ('code_hash', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('used', 'Использован'), ('expired', 'Истек'), ('invalidated', 'Аннулирован')], default='pending', max_length=15)),
                ('attempts_used', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('two_factor_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='users.twofactorauth')),
            ],
            options={
                'verbose_name': 'Код двухфакторной аутентификации',
                'verbose_name_plural': 'Коды двухфакторной аутентификации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('login_attempt', 'Попытка входа'), ('code_sent', 'Код отправлен'), ('code_verified', 'Код подтвержден'), ('code_failed', 'Код неверный'), ('backup_code_used', 'Использован резервный код'), ('two_factor_enabled', '2FA включена'), ('two_factor_disabled', '2FA отключена'), ('account_locked', 'Аккаунт заблокирован'), ('account_unlocked', 'Аккаунт разблокирован')], max_length=25)),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failed', 'Неудачно'), ('warning', 'Предупреждение'), ('info', 'Информация')], max_length=10)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('two_factor_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='users.twofactorauth')),
            ],
            options={
                'verbose_name': 'Лог двухфакторной аутентификации',
                'verbose_name_plural': 'Логи двухфакторной аутентификации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='users_user_user_ty_4573bb_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['registration_source'], name='users_user_registr_44bf21_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_user_created_cf865c_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['token'], name='users_passw_token_b56ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user', 'is_used'], name='users_passw_user_id_5ee9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['expires_at'], name='users_passw_expires_853bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='twofactorcode',
            index=models.Index(fields=['two_factor_auth', 'status', 'expires_at'], name='users_twofa_two_fac_e73f9c_idx'),
        ),
        migrations.AddIndex(
            model_name='twofactorcode',
            index=models.Index(fields=['uuid'], name='users_twofa_uuid_bdc7d3_idx'),
        ),
        migrations.AddIndex(
            model_name='twofactorlog',
            index=models.Index(fields=['two_factor_auth', 'log_type', 'created_at'], name='users_twofa_two_fac_c6208b_idx'),
        ),
        migrations.AddIndex(
            model_name='twofactorlog',
            index=models.Index(fields=['ip_address', 'created_at'], name='users_twofa_ip_addr_dfa549_idx'),
        ),
    ]
