# Generated by Django 5.2.7 on 2025-11-03 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdminAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_permissions', models.JSONField(blank=True, default=dict, help_text='Структурированные права доступа к приложениям и моделям', verbose_name='Права доступа к админке')),
                ('is_active', models.BooleanField(default=True, help_text='Если отключено, пользователь не имеет доступа к админке', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_access', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ к админке',
                'verbose_name_plural': 'Доступы к админке',
                'indexes': [models.Index(fields=['user', 'is_active'], name='users_usera_user_id_182cdb_idx')],
            },
        ),
    ]
