# Generated by Django 5.2.6 on 2025-12-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_useradminaccess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useradminaccess",
            name="admin_permissions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='JSON структура прав доступа. Формат: {"apps": {"app_label": {"models": {"ModelName": ["view", "add", "change", "delete"]}}}}',
                verbose_name="Права доступа к админке",
            ),
        ),
    ]
