# Generated by Django 5.2.6 on 2025-10-18 12:44

import apps.programs.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('short_description', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('program_type', models.CharField(choices=[('deinstitutionalization', 'Программы деинституционализации'), ('child_protection', 'Реформы систем защиты прав детей'), ('graduate_support', 'Профессиональная подготовка и поддержка выпускников'), ('alternative_care', 'Альтернативный уход'), ('prevention', 'Превенция'), ('advocacy', 'Адвокация'), ('humanitarian_aid', 'Гуманитарная помощь'), ('mental_health', 'Психическое здоровье'), ('children_villages', 'SOS Детские деревни'), ('crisis_homes', 'Кризисные и переходные дома'), ('family_strengthening', 'Программа укрепления семьи'), ('graduate_support_direction', 'Поддержка выпускников'), ('sos_parents_training', 'Подготовка SOS-родителей'), ('psychological_support', 'Психологическая и социальная помощь'), ('other', 'Другое')], max_length=30, verbose_name='Тип программы')),
                ('icon', models.FileField(blank=True, null=True, upload_to='programs/icons/', validators=[apps.programs.validators.validate_image_or_svg_file], verbose_name='Иконка')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='programs/images/', verbose_name='Главное изображение')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='programs/video_thumbnails/', verbose_name='Превью видео')),
                ('is_main_program', models.BooleanField(default=False, verbose_name='Основная программа')),
                ('content', models.TextField(blank=True, verbose_name='Подробное содержание')),
                ('target_audience', models.CharField(blank=True, max_length=200, verbose_name='Целевая аудитория')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Продолжительность')),
                ('author_name', models.CharField(blank=True, max_length=200, verbose_name='Имя автора')),
                ('author_title', models.CharField(blank=True, max_length=200, verbose_name='Должность автора')),
                ('quote', models.TextField(blank=True, verbose_name='Цитата')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProgramStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('title', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('description', models.TextField(verbose_name='Описание этапа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('icon', models.FileField(blank=True, null=True, upload_to='programs/steps/icons/', validators=[apps.programs.validators.validate_image_or_svg_file], verbose_name='Иконка этапа')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='programs.program', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Этап программы',
                'verbose_name_plural': 'Этапы программ',
                'ordering': ['order'],
            },
        ),
    ]
