# Generated by Django 5.2.6 on 2025-10-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL'),
        ),
    ]
