# Generated by Django 5.2.6 on 2025-10-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['number_of_questions'], 'verbose_name': 'Часто задаваемый вопрос', 'verbose_name_plural': 'Часто задаваемые вопросы'},
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(blank=True, verbose_name='Ответ (EN)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_kg',
            field=models.TextField(blank=True, verbose_name='Ответ (КГ)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вопрос (EN)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_kg',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вопрос (КГ)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='number_of_questions',
            field=models.IntegerField(default=1, unique=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Вопрос'),
        ),
    ]
