# Generated by Django 5.2.6 on 2025-10-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankingRequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('organization_type', models.CharField(choices=[('main_foundation', 'Основной фонд'), ('children_village', 'Детская деревня'), ('educational_center', 'Образовательный центр'), ('other', 'Другое')], default='main_foundation', max_length=50, verbose_name='Тип организации')),
                ('currency', models.CharField(choices=[('KGS', 'Кыргызский сом'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('RUB', 'Российский рубль')], max_length=3, verbose_name='Валюта')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('account_number', models.CharField(max_length=50, verbose_name='Номер счета')),
                ('bik', models.CharField(blank=True, max_length=20, verbose_name='БИК')),
                ('swift', models.CharField(blank=True, max_length=20, verbose_name='SWIFT')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('okpo', models.CharField(blank=True, max_length=20, verbose_name='ОКПО')),
                ('tax_office', models.CharField(blank=True, max_length=255, verbose_name='Налоговая инспекция')),
                ('correspondent_bank', models.CharField(blank=True, max_length=255, verbose_name='Корреспондентский банк')),
                ('correspondent_swift', models.CharField(blank=True, max_length=20, verbose_name='SWIFT корреспондентского банка')),
                ('correspondent_address', models.TextField(blank=True, verbose_name='Адрес корреспондентского банка')),
                ('correspondent_account', models.CharField(blank=True, max_length=50, verbose_name='Корреспондентский счет')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Банковский реквизит',
                'verbose_name_plural': 'Банковские реквизиты',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
