# Generated by Django 5.2.11 on 2026-03-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SOSFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Город/Регион')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='friends/photos/', verbose_name='Фото')),
                ('message', models.TextField(verbose_name='Сообщение/Отзыв')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Друг SOS',
                'verbose_name_plural': 'Друзья SOS',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
