# Generated by Django 5.2.11 on 2026-03-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendsos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sosfriend',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'История друга', 'verbose_name_plural': 'Истории наших друзей'},
        ),
    ]
