"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import quote
from datetime import timedelta
import environ


env = environ.Env(
    DEBUG=(bool, False)
)

# Try to read .env file, but don't fail if it doesn't exist (e.g., during Docker build)
import os
env_file = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), '.env')
if os.path.exists(env_file):
    environ.Env.read_env(env_file=env_file)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'unfold.contrib.import_export',
    'unfold.contrib.guardian',
    'unfold.contrib.simple_history',
    'unfold.contrib.location_field',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # DEPENDS
    'rest_framework',
    'corsheaders',
    'drf_spectacular',
    'rest_framework_simplejwt',
    'celery',
    'django_celery_beat',
    'psycopg2',
    'django_ckeditor_5',
    'django_filters',

    # DJANGO APPLICATION
    'apps.users',
    'apps.news',
    'apps.contacts',
    'apps.common',
    'apps.donations',
    'apps.donors',
    'apps.partners',
    'apps.vacancies',
    'apps.faq',
    'apps.locations',
    'apps.success_stories',
    'apps.programs',
    'apps.timeline',
    'apps.principles',
    'apps.impact_results',
    'apps.donation_options',
    'apps.social_networks',
    'apps.factories',
    'apps.banking_requisites',
    'apps.digital_campaigns',
    'apps.feedback',
    'apps.qrcode',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'apps.qrcode.middleware.SecurityMiddleware',  # Наш middleware безопасности
    'apps.qrcode.middleware.RequestLoggingMiddleware',  # Логирование запросов
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Django локализация
    'apps.common.middleware.language.LanguageMiddleware',  # Наш middleware
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'apps.users.middleware.TwoFactorSessionMiddleware',
    # 'apps.users.middleware.TwoFactorAdminMiddleware',
]


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USERNAME'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Локализация
LANGUAGE_CODE = 'ru'  # Основной язык - русский

LANGUAGES = [
    ('ru', 'Русский'),
    ('kg', 'Кыргызча'),
    ('en', 'English'),
]

# Добавляем поддержку кыргызского языка
EXTRA_LANG_INFO = {
    'kg': {
        'bidi': False,
        'code': 'kg',
        'name': 'Кыргызча',
        'name_local': 'Кыргызча',
    },
}

TIME_ZONE = 'Asia/Bishkek'  # Временная зона Кыргызстана

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Пути к файлам переводов
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'SOS KG API',
    'DESCRIPTION': 'API для фонда SOS Детские деревни Кыргызстана',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIXES': [
        r'/api/v1/',
    ],
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': False,
    'TAGS': [
        {'name': 'auth', 'description': 'Аутентификация, регистрация, 2FA'},
        {'name': 'users', 'description': 'Управление пользователями'},
        {'name': 'donations', 'description': 'Пожертвования, кампании и транзакции'},
        {'name': 'donors', 'description': 'F2F регистрации, координаторы и отчеты'},
        {'name': 'news', 'description': 'Новости, категории и теги'},
        {'name': 'contacts', 'description': 'Контакты и категории контактов'},
        {'name': 'partners', 'description': 'Партнеры организации'},
        {'name': 'vacancies', 'description': 'Вакансии'},
        {'name': 'faq', 'description': 'Часто задаваемые вопросы'},
        {'name': 'locations', 'description': 'Локации на карте Кыргызстана'},
    ],
}



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Настройки для загрузки файлов
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Поддержка SVG файлов
ALLOWED_IMAGE_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'bmp', 'svg', 'webp']
ALLOWED_IMAGE_MIME_TYPES = [
    'image/jpeg', 'image/png', 'image/gif', 'image/bmp', 
    'image/svg+xml', 'image/webp'
]

# Настройки безопасности
MAX_REQUEST_SIZE = 10 * 1024 * 1024  # 10MB
RATE_LIMIT_REQUESTS = 100  # Максимум запросов в минуту с одного IP

# Настройки для защиты от атак
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000  # 1 год
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Настройки для файлов
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')

# Celery settings
REDIS_PASSWORD = env("REDIS_PASSWORD")
ENCODED_REDIS_PASSWORD = quote(REDIS_PASSWORD, safe="")

REDIS_HOST = env("REDIS_HOST", default="redis")
REDIS_PORT = env("REDIS_PORT", default="6379")

CELERY_BROKER_URL = f"redis://:{ENCODED_REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0"
CELERY_RESULT_BACKEND = f"redis://:{ENCODED_REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/1"
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_RESULT_SERIALIZER = 'json'

# FreedomPay settings
FREEDOMPAY_BASE_URL = env('FREEDOMPAY_BASE_URL', default='https://api.freedompay.kg')
FREEDOMPAY_MERCHANT_ID = env('FREEDOMPAY_MERCHANT_ID', default='')
FREEDOMPAY_SECRET_KEY = env('FREEDOMPAY_SECRET_KEY', default='')
FREEDOMPAY_TEST_MODE = env('FREEDOMPAY_TEST_MODE', default=True)  # Включен для тестирования IP
FREEDOMPAY_MOCK_MODE = env('FREEDOMPAY_MOCK_MODE', default=False)  # Отключен для использования реальных данных
FREEDOMPAY_CLIENT_IP = env('FREEDOMPAY_CLIENT_IP', default='8.8.8.8')  # Публичный IP для тестирования

# Google reCAPTCHA v2 settings
RECAPTCHA_SITE_KEY = env('RECAPTCHA_SITE_KEY', default='')
RECAPTCHA_SECRET_KEY = env('RECAPTCHA_SECRET_KEY', default='')
RECAPTCHA_VERIFY_URL = 'https://www.google.com/recaptcha/api/siteverify'
SKIP_RECAPTCHA_IN_DEBUG = env('SKIP_RECAPTCHA_IN_DEBUG', default=True)  # Отключить reCAPTCHA в DEBUG режиме

# Site URL for redirects (moved to Site Settings section)
CELERY_TIMEZONE = 'UTC'

# Salesforce settings
SALESFORCE_USERNAME = env('SALESFORCE_USERNAME', default='')
SALESFORCE_PASSWORD = env('SALESFORCE_PASSWORD', default='')
SALESFORCE_SECURITY_TOKEN = env('SALESFORCE_SECURITY_TOKEN', default='')
SALESFORCE_DOMAIN = env('SALESFORCE_DOMAIN', default='login')  # 'login' for production, 'test' for sandbox
SALESFORCE_VERSION = env('SALESFORCE_VERSION', default='60.0')
SALESFORCE_MOCK_MODE = env('SALESFORCE_MOCK_MODE', default=True)  # Mock режим для разработки

# CKEditor 5 settings
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote'],
        'height': 300,
        'width': '100%',
    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': [
            'heading', '|',
            'outdent', 'indent', '|',
            'bold', 'italic', 'link', 'underline', 'strikethrough', 'code', 'subscript', 'superscript', 'highlight', '|',
            'codeBlock', 'sourceEditing', '|',
            'bulletedList', 'numberedList', 'todoList', '|',
            'blockQuote', 'insertImage', '|',
            'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', '|',
            'alignment', '|',
            'horizontalLine', '|',
            'removeFormat', '|',
            'undo', 'redo',
        ],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:alignBlockLeft', 'imageStyle:alignBlockRight', 'imageStyle:block', 'imageStyle:inline', '|', 'toggleImageCaption', 'imageLink']
        },
        'table': {
            'contentToolbar': [
                'tableColumn',
                'tableRow',
                'mergeTableCells',
                'tableProperties',
                'tableCellProperties'
            ]
        },
        'height': 300,
        'width': '100%',
    }
}

CKEDITOR_5_UPLOAD_PATH = 'uploads/'
# SIMPLE JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(days=1),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}

# Two-Factor Authentication Settings
TWO_FACTOR_ENCRYPTION_KEY = env('TWO_FACTOR_ENCRYPTION_KEY', default=None)
TWO_FACTOR_CODE_EXPIRY_MINUTES = 5
TWO_FACTOR_MAX_ATTEMPTS = 5
TWO_FACTOR_LOCKOUT_MINUTES = 30
TWO_FACTOR_RATE_LIMIT_ATTEMPTS = 3
TWO_FACTOR_RATE_LIMIT_WINDOW_MINUTES = 60

# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@sos-kg.org')

# Site Settings
SITE_URL = env('SITE_URL', default='https://api.sos-kyrgyzstan.org')


CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'https://localhost:3000',
    'https://sos-kg.vercel.app',
    'https://sos-nomadpro.vercel.app',
    'https://sos-kyrgyzstan.org',
    'https://www.sos-kyrgyzstan.org',
    'http://167.99.245.121:3000'
]

CORS_ALLOW_CREDENTIALS = True

FRONTEND_URL=env('FRONTEND_URL', default='http://localhost:3000')
