# Generated by Django 5.2.6 on 2025-10-18 12:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('year', models.CharField(max_length=20, verbose_name='Год')),
                ('title', models.CharField(max_length=200, verbose_name='Название события')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('event_type', models.CharField(choices=[('foundation', 'Основание'), ('opening', 'Открытие'), ('launch', 'Запуск'), ('anniversary', 'Юбилей'), ('program', 'Программа'), ('expansion', 'Расширение'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип события')),
                ('image', models.ImageField(blank=True, null=True, upload_to='timeline/', verbose_name='Изображение')),
                ('icon', models.CharField(blank=True, help_text='Название иконки для отображения', max_length=50, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Место')),
                ('participants', models.CharField(blank=True, max_length=200, verbose_name='Участники')),
                ('impact', models.TextField(blank=True, verbose_name='Влияние/Результат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Событие временной шкалы',
                'verbose_name_plural': 'События временной шкалы',
                'ordering': ['order', 'year'],
            },
        ),
    ]
